spring:
  application:
    name: checkit
  jpa:
    database: "mysql"
    show-sql: "true"
    hibernate:
      ddl-auto: "update"
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
  data:
    mongodb:
      uri: "mongodb+srv://bookUser:xKgdAU059SogYFXb@book.bzk2tum.mongodb.net/book?retryWrites=true&w=majority"

  datasource:
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    url: "jdbc:mysql://localhost:3306/checkit"
    username: "root"
    password: "0000"

